FROM reigncl/airflow:2.7.2-python3.11-onbuild

USER root
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B7B3B788A8D3785C
RUN apt-get update 
RUN apt-get install default-jre -y
RUN apt-get install python3-dev -y
ENV JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk/"
ENV LD_LIBRARY_PATH="/usr/lib/jvm/java-8-openjdk/jre/lib/amd64/server/"

USER airflow
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt
