SELECT P.SKU_KEY
	, P.EAN 
	, P.CONT_CONV_UMB
	, P.NM
	, P.BRAND_DESC
	, P.UNIDAD_DE_MEDIDA
FROM DWC_SMU.SMU.VW_DIM_PRODUCT P
WHERE (P.NLS_PD_DSC IS NOT NULL OR P.UNIDAD_DE_MEDIDA IN ('KG', 'KGV'))
AND P.UNIDAD_DE_MEDIDA  IS NOT NULL
AND p.indic_ean_ppal = 'X';
