SELECT S.NBR_ITM 
	, S.SKU_HEX as SKU_KEY
	, SA.SKU_PRODUCT 
	, OU.OU_ID 
FROM cl-cda-prod.DS_CDA_VW_SMU.DW_VW_FACT_STOCK S
LEFT JOIN cl-cda-prod.DS_CDA_VW_SMU.DW_VW_DIM_SKU_ATTR SA ON SA.SKU_KEY  = S.SKU_KEY
LEFT JOIN cl-cda-prod.DS_CDA_VW_SMU.DW_VW_DIM_ORGANIZATION_UNIT OU ON OU.OU_KEY = S.OU_KEY
LEFT JOIN cl-cda-prod.DS_CDA_VW_SMU.DW_VW_DIM_ORGANIZATION O ON OU.ORG_KEY = O.ORGANIZATION_KEY
LEFT JOIN cl-cda-prod.DS_CDA_VW_SMU.DW_VW_DIM_ALMACEN A ON A.ALMACEN_KEY =S.ALMACEN_KEY
LEFT JOIN cl-cda-prod.DS_CDA_VW_SMU.DW_VW_DIM_PARTICULARIDAD PART ON S.PARTICULARIDAD_KEY =PART.PARTICULARIDAD_KEY
WHERE OU.OU_ID in {store_ids}
AND O.PRIM_CMRCL_NM IN ('Unimarc') 
AND S.DATE_VALUE = '{exec_date}'
AND S.APLICA_STOCK = 'S'
AND A.ALMACEN_COD = '0001'
AND S.TIPO_STOCK_KEY = MD5('TIPOSTOCK^CL^SMC^')
AND PART.PARTICULARIDAD_COD = 'A'
AND S.NBR_ITM > 0
;
